# Project Information
name: pharmacy_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

# Dart & Flutter Environment
environment:
  sdk: ^3.10.0

# Dependencies
dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.12.0
  iconsax_flutter: ^1.0.1
  google_fonts: ^6.3.2
  gap: ^3.0.1
  flutter_animate: ^4.5.2
  smooth_page_indicator: ^1.2.1
  

  # Navigation
  go_router: ^17.0.0

  # Storage
  shared_preferences: ^2.2.2

  # Utilities
  logger: ^2.6.2
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3

  # Forms & Inputs
  flutter_form_builder: ^10.2.0
  flutter_intl_phone_field: ^0.0.7

  # Localization
  flutter_localizations:
    sdk: flutter
  dio: ^5.9.0
  photo_view: ^0.15.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  pretty_dio_logger: ^1.4.0
  flutter_bloc: ^9.1.1

# Dev Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# Flutter Settings
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/products_image/
    - assets/banners/
    - assets/images/

  fonts:
    - family: CairoBold
      fonts:
        - asset: assets/fonts/Cairo-Bold1.ttf
          weight: 700
          style: normal

# Internationalization
flutter_intl:
  enabled: true
